name: Publish Nodes

on:
  #schedule:
 #  - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  Publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 16.0
    - name: publish
      env: 
        PAIMONNODE_DB_URI: ${{ secrets.PAIMONNODE_DB_URI }}
      run: cd ./publish && npm ci && npm run run
    - name: Configure Git
      run: git config pull.rebase false && git config --local user.name "GitHub Actions" && git config --local user.email "actions@github.com"
    - run: chmod 777 ./publish/up.sh
    - run: cp ./publish/clash.yaml .
    - run: cp ./publish/base64 .
    - run: ./publish/up.sh
